# Generated by Django 4.2.3 on 2023-07-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_customers_orders_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('size', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('zodiac', 'Zodiac'), ('flowering', 'Flowering'), ('low_maintain', 'Low_Maintenance'), ('medicinal', 'Medicinal'), ('air_purifying', 'Air_Purifying')], max_length=50)),
                ('sunlight', models.CharField(max_length=1000)),
                ('water', models.CharField(max_length=1000)),
                ('fertilizer', models.CharField(max_length=1000)),
                ('shortdesc', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.plants'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
