# Generated by Django 4.2.3 on 2023-07-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_plants_remove_products_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='subcategory',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='Indoor', max_length=50),
        ),
    ]
