# Generated by Django 4.2.3 on 2023-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_plants_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='size',
            field=models.CharField(choices=[('large', 'Large'), ('medium', 'Medium'), ('small', 'Small')], max_length=50),
        ),
    ]
