# Generated by Django 4.2.3 on 2023-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_plants_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='temperature',
            field=models.CharField(default='', max_length=100),
        ),
    ]
