# Generated by Django 4.2.3 on 2023-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_plants_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='images',
            field=models.ImageField(default='', upload_to='plants/images'),
        ),
    ]
