# Generated by Django 4.2.3 on 2023-08-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_plants_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='plant/images'),
        ),
    ]
