# Generated by Django 4.2.3 on 2023-08-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_plants_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='mainCategory',
            field=models.CharField(choices=[('plant', 'Plants'), ('pots', 'Pots'), ('tools', 'Tools'), ('fertilizers', 'Fertilizers')], default='Plants', max_length=100),
        ),
    ]
