# Generated by Django 4.2.3 on 2023-09-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_plants_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
