# Generated by Django 4.2.3 on 2023-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_plants_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
