# Generated by Django 4.2.3 on 2023-09-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_plants_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to='plants/images'),
        ),
        migrations.CreateModel(
            name='LikePlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedPlants', models.DateTimeField(auto_now=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customers')),
                ('plantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.plants')),
            ],
        ),
    ]
