# Generated by Django 4.2.3 on 2023-09-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_plants_images_likeplants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePlants',
            new_name='WishList',
        ),
    ]
