# Generated by Django 4.2.3 on 2023-09-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_products_remove_plants_maincategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customerId', 'plantId')},
        ),
    ]
