# Generated by Django 4.2.3 on 2023-09-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mainCategory',
            field=models.CharField(choices=[('Fertilizers', 'Fertilizers'), ('Tools', 'Tools'), ('Pots', 'Pots')], default='Fertilizers', max_length=100),
        ),
    ]
