# Generated by Django 4.2.3 on 2023-09-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_products_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mainCategory',
            field=models.CharField(choices=[('fertilizers', 'Fertilizers'), ('tools', 'Tools'), ('pots', 'Pots')], default='Fertilizers', max_length=100),
        ),
    ]
