# Generated by Django 4.2.3 on 2023-09-16 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_products_maincategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='plant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.plants'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='productId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.products'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customerId', 'plantId', 'productId')},
        ),
    ]
