# Generated by Django 4.2.3 on 2023-09-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_orders_plant_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='plantId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.plants'),
        ),
    ]
