# Generated by Django 4.2.3 on 2023-09-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_wishlist_plantid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
