# Generated by Django 4.2.3 on 2023-09-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_rename_user_cart_customer_remove_cart_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recentlyViewedTime', models.DateTimeField(auto_now=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customers')),
                ('plantId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.plants')),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.products')),
            ],
        ),
    ]
