# Generated by Django 4.2.3 on 2023-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_userrecentlyviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='password',
            new_name='zipCode',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.CharField(default='jogeshwari', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.CharField(default='mumbai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='fullName',
            field=models.CharField(default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='customers',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
            preserve_default=False,
        ),
    ]
